services:
  reallife-mysql:
    image: mysql:8.4
    container_name: reallife-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: backend
    volumes:
      - reallife_mysql_data:/var/lib/mysql

volumes:
  reallife_mysql_data: