spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

  datasource:
    url: jdbc:mysql://localhost:3306/backend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: YOUR_MYSQL_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: BINARY
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

jwt:
  secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_64_CHARS_MIN_0123456789abcdef"
  access-token-exp-minutes: 60

file:
  upload-dir: uploads

logging:
  level:
    org.flywaydb: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  cookie:
    secure-mode: auto
    same-site: Lax
    # domain: ""          # 필요하면 ".example.com"
    access-max-age-seconds: 900
    refresh-max-age-seconds: 1209600
    refresh-path: /api/auth
  public-base-url: http://localhost
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000